# Generated by Django 5.1.5 on 2025-01-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_customuser_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='fotos_perfil/default_profile.jpg', null=True, upload_to='fotos_perfil/'),
        ),
    ]
